### ISSUE TITLE
Broken build on Ubuntu 11.10

### ISSUE THREAD

**Issue by l3iggs** [hbons/SparkleShare#456]
```
$ make
Making all in build
Making all in m4
Making all in help
Making all in SparkleLib
  MCS   ../bin/SparkleLib.dll
Making all in data
Making all in icons
Making all in html
Making all in plugins
Making all in po
Making all in SparkleShare
Making all in Nautilus
Making all in Mac
  MCS   ../bin/SparkleShare.exe
./SparkleSetup.cs(90,33): error CS0103: The name `CheckSetupPage' does not exist in the current context
./SparkleSetup.cs(72,21): error CS0163: Control cannot fall through from one case label to another
./SparkleSetup.cs(271,29): error CS0103: The name `CheckAddPage' does not exist in the current context
./SparkleSetup.cs(72,21): error CS0163: Control cannot fall through from one case label to another
Compilation failed: 4 error(s), 0 warnings
make[2]: *** [../bin/SparkleShare.exe] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```
