### ISSUE TITLE
Can't build on Ubuntu 11.10

### ISSUE THREAD

**Issue by gjedeer** [hbons/SparkleShare#394]
./SparkleConfig.cs(76,15): error CS0160: A previous catch clause already catches all exceptions of this or a super type `System.IO.IOException'
Compilation failed: 1 error(s), 0 warnings
