### ISSUE TITLE
Compile on Ubuntu 12.04

### ISSUE THREAD

**Issue by mikabytes** [hbons/SparkleShare#979]
Hi. I could compile SparkleShare just fine on my Ubuntu 11.04 machine, however for the 12.04 one it failes on the `make` stage:

```
sparkleshare$ make
Making all in build
Making all in m4
Making all in SparkleLib
  MCS   ../bin/SparkleLib.dll
Making all in SparkleLib/Git
  MCS   ../../bin/SparkleLib.Git.dll
Making all in SparkleShare
Making all in Linux
Making all in Nautilus
Making all in Pixmaps
Making all in icons
Making all in ubuntu-mono-dark
Making all in ubuntu-mono-light
  MCS   ../../bin/SparkleShare.exe
./SparkleStatusIcon.cs(185,42): error CS1061: Type `Gtk.Widget' does not contain a definition for `Add' and no extension method `Add' of type `Gtk.Widget' could be found (are you missing a using directive or an assembly reference?)
/usr/lib/cli/gtk-sharp-2.0/gtk-sharp.dll (Location of the symbol related to previous error)
./SparkleStatusIcon.cs(217,42): error CS1061: Type `Gtk.Widget' does not contain a definition for `Add' and no extension method `Add' of type `Gtk.Widget' could be found (are you missing a using directive or an assembly reference?)
/usr/lib/cli/gtk-sharp-2.0/gtk-sharp.dll (Location of the symbol related to previous error)
Compilation failed: 2 error(s), 0 warnings
make[3]: *** [../../bin/SparkleShare.exe] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

On both systems the gtk-sharp2 package was installed. Perhaps the API has changed between these versions. Can anyone confirm that SparkleShare can be built on Ubuntu 12.04 with the instructions given here? Thanks.
