### ISSUE TITLE
Doesn't compile due to duplicate code

### ISSUE THREAD

**Issue by maleadt** [hbons/SparkleShare#22]
SparkleShare doesn't compile on mono 2.6 due to some duplicate code in SparkleController.cs

> ./SparkleController.cs(29,1): warning CS0105: The using directive for `System.Net' appeared previously in this namespace
> ./SparkleController.cs(24,14): (Location of the symbol related to previous warning)
> ./SparkleLog.cs(474,22): error CS0101: The namespace`SparkleShare' already contains a definition for `ActivityDay'
> ./SparkleController.cs(1080,22): (Location of the symbol related to previous error)

Removing the code in SparkleController.cs makes everything compile again.
