### ISSUE TITLE
Master does not compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by aggsol** [hbons/SparkleShare#1725]
After autogen and configure the following compile error occurs:

`/UserInterface.cs(65,47): error CS1502: The best overloaded method match for GLib.Application.Run(int, string)' has some invalid arguments`

The call is:

```
        public void Run ()
        {   
            (application as GLib.Application).Run ("org.sparkleshare.SparkleShare", new string [0]);
        }
```

As this is very basic GLib code I am wondering if Sparkleshare needs some old legacy version?

**Comment by hbons** [comment]
what version of gtk/glib is installed?

**Comment by aggsol** [comment]
I have the packages glib-sharp-3.0 2.99.3 and gtk-sharp-3.0 2.99.3

**Comment by dschoeffm** [comment]
Is there any update on this issue? I am currently having the same problem with openSUSE Leap 42.2 using the same package versions.

**Comment by hbons** [comment]
Not yet... I don't think this line is critical. Can you try changing that call so it works for you? Don't have access to a Linux computer now so can't really test.

**Comment by dschoeffm** [comment]
Sorry I confused some different sparkleshare versions on my hard drive. For the master I'm also suffering issue #1742. The version I tried to compile was SparkleShare 1.5 as downloaded from https://bitbucket.org/hbons/sparkleshare/downloads/sparkleshare-linux-1.5.tar.gz (found on https://www.sparkleshare.org/)

Actually the line is critical, since the compilation is aborted.

The line seems to correspond to
`public int Run (int argc, string argv)`

and I changed it to
`(this.application as GLib.Application).Run (0, "");`

After the change the program compiles and launches without any errors, but crashes as soon as I click on the tray icon. This is the error given in the terminal:
```
(mono:16739): GLib-CRITICAL **: Source ID 34 was not found when attempting to remove it
```

Notably the application starts when I use `mono "bin/SparkleShare.exe"` and `mono "bin/SparkleShare.exe" help`, but `mono "bin/SparkleShare.exe" start` shows the help text.

**Comment by dschoeffm** [comment]
The line actually prohibits the program from compiling.
Well I tried, but my C# is pretty much non-existent. the line `(application as GLib.Application).Run (1, "org.sparkleshare.SparkleShare");` compiles but crashes on startup. The same error is also present in version 1.5 (as downloaded from https://www.sparkleshare.org/)

**Comment by City-busz** [comment]
Replacing line
`            (application as GLib.Application).Run ("org.sparkleshare.SparkleShare", new string [0]);`
with
`            (application as GLib.Application).Run (0, null);`
solves the problem.

**Comment by grafi-tt** [comment]
I also confirmed this problem, and @City-busz's patch worked like a charm. Any progress?

**Comment by hbons** [comment]
Fixed in master. Seems that different distros use different versions of gtk-sharp and the API is slightly different. Sticking with Ubuntu's version for now.

**Comment by hbons** [comment]
I now remember why I changed this: building a flatpak uses a newer gtk-sharp and so a slightly newer API. Pushed a hack to work on both in 37207ce.

**Comment by City-busz** [comment]
I think that 020c6db will break the build on other distributions.

@hbons Could you please make a distibution-agnostic solution by testing the gtk-sharp API version instead?

**Comment by hbons** [comment]
@City-busz I've no idea how to do that. If someone can take a look at it that would be great. I can only guarantee Ubuntu and Fedora.
